# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 848db6e60c1ea34a406b6c54054ba5255a9bc921f5eda8fcc71c20c72611b1510420c5569a5a265bf11a8217166cd5775fe674618104f6a36fd94539535a1b83

test:
  secret_key_base: 54fed4e44f5c4261db49c357b7db373ce33801cb11047ca592de9035ebeee125aced75d615768f8eef1f46e1a2d885c4b1f6a2c63da7b0a8233d79a7da5de31e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
